apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sparkjava.saikrish.xyz
  namespace: sparkjava
spec:
  secretName: sparkjava.saikrish.xyz-tls
  issuerRef:
    name: sparkjava-issuer
    kind: ClusterIssuer
  commonName: sparkjava.saikrish.xyz
  dnsNames:
  - sparkjava.saikrish.xyz
