apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: sparkjava-issuer
  namespace: sparkjava
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: saikrish9966793136@gmail.com
    privateKeySecretRef:
      name: sparkjava-issuer
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
